import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import NextSessionProvider from "@/components/NextSessionProvider/NextSessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "The Edge Of Thoughts",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + " min-h-screen flex flex-col"}>
        <NextSessionProvider>
          <div className="navbar-div top-0 z-50 fixed pb-2 w-full bg-orange-50 shadow-lg md:py-0 py-2 px-4">
            <Navbar></Navbar>
          </div>
          <div className="layout-div mt-28">{children}</div>
          {/* <div className="footer-div mt-auto">
            <Footer></Footer>
          </div> */}
        </NextSessionProvider>
      </body>
    </html>
  );
}
